steps:
- name: 'docker.io/library/python:latest'
  entrypoint: 'bash'
  args:
   - -c
   - |
     pip install -r requirements.txt
     python manage.py test --verbosity=2 --noinput
  env: ['BETTERSTART_DB=local']
