steps:
- name: 'docker.io/library/python:3'
  entrypoint: 'bash'
  args: ['install_and_test.sh']
  env: ['BETTERSTART_DB=local']
- name: 'docker.io/library/python:3'
  args: ['python','build_yaml.py']
- name: 'docker.io/library/python:3'
  entrypoint: 'bash'
  args: ['cat','app.yaml']
