steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test_runner', '.']
- name: 'gcr.io/$PROJECT_ID/test_runner'
  entrypoint: 'bash'
  args:
   - -c
   - |
      curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
      chmod +x cloud_sql_proxy
      ./cloud_sql_proxy -instances $$BETTERSTART_DB_INSTANCE=tcp:3306 &
      python manage.py test --verbosity=2 --noinput
  env:
    - BETTERSTART_DB=local
    - BETTERSTART_DB_INSTANCE=${_BETTERSTART_DB_INSTANCE}
