steps:
  env: ['BETTERSTART_DB=local']
- name: 'docker.io/library/python:3'
  args: ['python','build_yaml.py']
  env: ['BETTERSTART_PW=test']
- name: 'docker.io/library/python:3'
  args: ['cat','app.yaml']
- name: 'docker.io/library/ubuntu'
  entrypoint: 'bash'
  args:
   - -c
   - |
     python build_yaml.py
     cat app.yaml