steps:
# run test locally
- name: gcr.io/$PROJECT_ID/test_runner
  args: ['python','manage.py','test','--verbosity=2','--noinput']
  env: ['BETTERSTART_DB=local']
# decrypt environment variables
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=${_BETTERSTART_ENV_SCRIPT}
  - --plaintext-file=setenv
  - --location=global
  - --keyring=betterstart-keyring
  - --key=betterstart-key
# test against Cloud SQL
- name: gcr.io/$PROJECT_ID/test_runner
  entrypoint: 'bash'
  args:
   - -c
   - |
      . setenv
      /cloud_sql_proxy -instances $$BETTERSTART_DB_INSTANCE=tcp:3306 &
      python manage.py test --verbosity=2 --noinput
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
# prep for deployment
- name: gcr.io/$PROJECT_ID/test_runner
  entrypoint: 'bash'
  args:
   - -c
   - |
      . setenv
      python manage.py collectstatic --noinput
      python build_yaml.py
      /cloud_sql_proxy -instances $$BETTERSTART_DB_INSTANCE=tcp:3306 &
      python manage.py migrate --noinput
# deploy application to App Engine
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy']
