# Generated by Django 2.1.5 on 2019-04-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.AddField(
            model_name='person',
            name='default_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Role_Type'),
            preserve_default=False,
        ),
    ]
