# Generated by Django 2.1.5 on 2019-05-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_abss_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ABSS_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='people.ABSS_Type'),
        ),
    ]
