# Generated by Django 2.1.5 on 2019-04-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_role_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_history',
            name='person',
        ),
        migrations.RemoveField(
            model_name='role_history',
            name='role_type',
        ),
        migrations.DeleteModel(
            name='Role_History',
        ),
    ]
