# Generated by Django 2.1.5 on 2019-05-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_abss_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Age statuses',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='age_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='people.Age_Status'),
        ),
    ]
