# Generated by Django 2.1.5 on 2019-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190217_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='families',
            field=models.ManyToManyField(blank=True, to='people.Family'),
        ),
    ]
