# Generated by Django 2.1.5 on 2019-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190512_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='trained_champion',
            field=models.BooleanField(default=False),
        ),
    ]
