# Generated by Django 2.1.5 on 2019-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_abss_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABSS_Type',
        ),
    ]
