# Generated by Django 2.1.5 on 2019-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190518_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Role_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_role_type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'event role types',
            },
        ),
        migrations.AlterModelOptions(
            name='role_history',
            options={'verbose_name_plural': 'role histories'},
        ),
    ]
