# Generated by Django 2.1.5 on 2019-05-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190518_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_type',
            name='use_for_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role_type',
            name='use_for_people',
            field=models.BooleanField(default=False),
        ),
    ]
