# Generated by Django 2.1.5 on 2019-05-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190519_0157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Role_Type',
        ),
    ]
