# Generated by Django 2.1.5 on 2019-05-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_delete_event_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='people.Post_Code')),
            ],
            options={
                'verbose_name_plural': 'streets',
            },
        ),
    ]
