# Generated by Django 2.1.5 on 2019-05-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='house_name_or_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Street'),
        ),
    ]
