# Generated by Django 2.1.5 on 2019-05-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190523_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='address',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='addresses',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Residence',
        ),
    ]
