# Generated by Django 2.1.5 on 2019-06-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190525_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='capture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Capture_Type'),
        ),
    ]
