# Generated by Django 2.1.5 on 2019-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190601_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='notes_label',
            field=models.CharField(default='Notes', max_length=30),
        ),
    ]
