# Generated by Django 2.1.5 on 2019-07-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190728_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Question')),
            ],
            options={
                'verbose_name_plural': 'answers',
            },
        ),
    ]
