# Generated by Django 2.2.4 on 2019-08-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_answer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='english_is_second_language',
        ),
    ]
