# Generated by Django 2.2.4 on 2019-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_remove_person_english_is_second_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
