# Generated by Django 2.2.4 on 2019-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_event_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='areas',
            field=models.ManyToManyField(to='people.Area'),
        ),
    ]
