# Generated by Django 2.2.4 on 2019-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_event_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='use_for_events',
            field=models.BooleanField(default=False),
        ),
    ]
