# Generated by Django 2.2.4 on 2019-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_area_use_for_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='role_types',
            field=models.ManyToManyField(to='people.Role_Type'),
        ),
    ]
