# Generated by Django 2.2.4 on 2019-08-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_age_status_role_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_type',
            name='default_for_age_status',
            field=models.BooleanField(default=False),
        ),
    ]
