# Generated by Django 2.2.4 on 2019-08-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_role_type_default_for_age_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='can_be_parent_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='age_status',
            name='can_be_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='age_status',
            name='can_have_contact_details',
            field=models.BooleanField(default=False),
        ),
    ]
