# Generated by Django 2.2.4 on 2019-08-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20190824_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='maximum_age',
            field=models.IntegerField(default=999),
        ),
    ]
