# Generated by Django 2.2.4 on 2019-08-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_age_status_maximum_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='default_role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_status_default', to='people.Role_Type'),
        ),
        migrations.AddField(
            model_name='age_status',
            name='default_role_type_only',
            field=models.BooleanField(default=False),
        ),
    ]
