# Generated by Django 2.2.4 on 2019-08-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20190825_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_type',
            name='default_for_age_status',
        ),
    ]
