# Generated by Django 2.2.4 on 2019-09-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_remove_role_type_default_for_age_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trained_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='role_type',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='trained_role',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Role_Type'),
        ),
        migrations.AddField(
            model_name='person',
            name='trained_roles',
            field=models.ManyToManyField(related_name='trained_people', through='people.Trained_Role', to='people.Role_Type'),
        ),
    ]
