# Generated by Django 2.2.4 on 2019-10-12 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20190907_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_note',
            options={'verbose_name_plural': 'answer notes'},
        ),
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
