# Generated by Django 2.2.4 on 2019-10-12 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20191012_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='datetime_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
