# Generated by Django 2.2.4 on 2019-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20191012_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
