# Generated by Django 2.2.4 on 2019-10-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_auto_20191012_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ABSS_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
