# Generated by Django 2.2.4 on 2019-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_person_abss_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_contact_details',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
