# Generated by Django 2.2.4 on 2019-11-23 13:22

from django.db import migrations, models
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_person_emergency_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('navbar_background', models.CharField(blank=True, max_length=50)),
            ],
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
