# Generated by Django 2.2.4 on 2019-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_site_navbar_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
