# Generated by Django 2.2.4 on 2019-12-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_auto_20191201_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_left',
        ),
    ]
