# Generated by Django 3.0 on 2019-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_auto_20191201_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='apologies',
            field=models.BooleanField(default=False),
        ),
    ]
