# Generated by Django 3.0 on 2019-12-26 10:17

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_auto_20191215_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'activity role_types',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Activity_Type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
