# Generated by Django 3.0 on 2019-12-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_type',
            options={'verbose_name_plural': 'activity types'},
        ),
    ]
