# Generated by Django 3.0 on 2020-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_auto_20191226_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='messages',
            field=models.BooleanField(default=False),
        ),
    ]
