# Generated by Django 3.0.2 on 2020-01-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_auto_20200119_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name_plural': 'events'},
        ),
    ]
