# Generated by Django 3.0.2 on 2020-02-04 21:23

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_age_status_relationship_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Column_Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'dashboard column inclusions',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dashboard_Column_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('count_field', models.CharField(max_length=50)),
                ('date_field', models.CharField(max_length=50)),
                ('date_filter', models.CharField(choices=[('', 'no date filter'), ('this_month', 'this month'), ('last_month', 'last_month'), ('this_project_year', 'this project year'), ('last_project_year', 'last project year'), ('this_calendar_year', 'this calendar year'), ('last_calendar_year', 'last_calendar_year')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'dashboard column specs',
                'ordering': ['title'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Filter_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'filter specs',
                'ordering': ['term'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dashboard_Panel_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('title_url', models.CharField(blank=True, default='', max_length=50)),
                ('title_icon', models.CharField(blank=True, default='', max_length=50)),
                ('show_column_names', models.BooleanField(default=False)),
                ('label_width', models.IntegerField(default=6)),
                ('column_width', models.IntegerField(default=6)),
                ('right_margin', models.IntegerField(default=0)),
                ('row_url', models.CharField(blank=True, default='', max_length=50)),
                ('row_parameter_name', models.CharField(blank=True, default='', max_length=50)),
                ('totals', models.BooleanField(default=False)),
                ('display_zeroes', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=50)),
                ('date_filter', models.CharField(choices=[('', 'no date filter'), ('this_month', 'this month'), ('last_month', 'last_month'), ('this_project_year', 'this project year'), ('last_project_year', 'last project year'), ('this_calendar_year', 'this calendar year'), ('last_calendar_year', 'last_calendar_year')], max_length=50)),
                ('date_field', models.CharField(max_length=50)),
                ('columns', models.ManyToManyField(through='people.Dashboard_Column_Inclusion', to='people.Dashboard_Column_Spec')),
                ('filters', models.ManyToManyField(to='people.Filter_Spec')),
            ],
            options={
                'verbose_name_plural': 'dashboard panel specs',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.AddField(
            model_name='dashboard_column_spec',
            name='filters',
            field=models.ManyToManyField(to='people.Filter_Spec'),
        ),
        migrations.AddField(
            model_name='dashboard_column_inclusion',
            name='dashboard_column_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Column_Spec'),
        ),
        migrations.AddField(
            model_name='dashboard_column_inclusion',
            name='dashboard_panel_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Panel_Spec'),
        ),
    ]
