# Generated by Django 3.0.2 on 2020-02-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_auto_20200204_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_column_spec',
            name='filters',
            field=models.ManyToManyField(blank=True, to='people.Filter_Spec'),
        ),
    ]
