# Generated by Django 3.0.2 on 2020-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_dashboard_panel_spec_row_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_panel_spec',
            name='sort_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
