# Generated by Django 3.0.2 on 2020-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0053_dashboard_panel_spec_sort_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_spec',
            name='value',
        ),
        migrations.AddField(
            model_name='filter_spec',
            name='boolean_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filter_spec',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('boolean', 'boolean'), ('period', 'period')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='filter_spec',
            name='period',
            field=models.CharField(blank=True, choices=[('', 'no period'), ('this_month', 'this month'), ('last_month', 'last_month'), ('this_project_year', 'this project year'), ('last_project_year', 'last project year'), ('this_calendar_year', 'this calendar year'), ('last_calendar_year', 'last_calendar_year')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='filter_spec',
            name='string_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
