# Generated by Django 3.0.2 on 2020-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0054_auto_20200208_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_column_spec',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='dashboard_column_spec',
            name='date_filter',
        ),
        migrations.RemoveField(
            model_name='dashboard_panel_spec',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='dashboard_panel_spec',
            name='date_filter',
        ),
        migrations.AlterField(
            model_name='dashboard_panel_spec',
            name='row_name_field',
            field=models.CharField(max_length=50),
        ),
    ]
