# Generated by Django 3.0.2 on 2020-02-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0056_auto_20200216_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard_panel_column_inclusion',
            old_name='dashboard_column_spec',
            new_name='dashboard_panel_column_spec',
        ),
    ]
