# Generated by Django 3.0.3 on 2020-02-16 10:41

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0057_auto_20200216_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Column_Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'dashboard column inclusions',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dashboard_Column_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'dashboard column specs',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dashboard_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('columns', models.ManyToManyField(through='people.Dashboard_Column_Inclusion', to='people.Dashboard_Column_Spec')),
            ],
            options={
                'verbose_name_plural': 'dashboard column specs',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dashboard_Panel_Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('dashboard_column_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Column_Spec')),
                ('dashboard_panel_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Panel_Spec')),
            ],
            options={
                'verbose_name_plural': 'dashboard panel inclusions',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.AddField(
            model_name='dashboard_column_spec',
            name='panels',
            field=models.ManyToManyField(through='people.Dashboard_Panel_Inclusion', to='people.Dashboard_Panel_Spec'),
        ),
        migrations.AddField(
            model_name='dashboard_column_inclusion',
            name='dashboard_column_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Column_Spec'),
        ),
        migrations.AddField(
            model_name='dashboard_column_inclusion',
            name='dashboard_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Dashboard_Spec'),
        ),
    ]
