# Generated by Django 3.0.3 on 2020-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0059_auto_20200216_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_column_spec',
            name='margins',
            field=models.IntegerField(default=1),
        ),
    ]
