# Generated by Django 3.0.3 on 2020-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0060_dashboard_column_spec_margins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard_spec',
            options={'ordering': ['name'], 'verbose_name_plural': 'dashboard specs'},
        ),
        migrations.AddField(
            model_name='dashboard_spec',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
