# Generated by Django 3.0.3 on 2020-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0061_auto_20200216_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_column_spec',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
