# Generated by Django 3.0.3 on 2020-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0063_auto_20200217_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_panel_column_spec',
            name='query_type',
            field=models.CharField(blank=True, choices=[('query from one', 'query from one'), ('query from many', 'query from many')], default='query from one', max_length=50),
        ),
    ]
