# Generated by Django 3.0.3 on 2020-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0064_dashboard_panel_column_spec_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_panel_spec',
            name='prebuilt_panel',
            field=models.CharField(blank=True, choices=[('Parent Exceptions', 'Parent_Exceptions_Panel')], default='', max_length=50),
        ),
    ]
