# Generated by Django 3.0.3 on 2020-02-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_dashboard_panel_spec_prebuilt_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_panel_spec',
            name='prebuilt_panel',
            field=models.CharField(blank=True, choices=[('Parent_Exceptions_Panel', 'Parent Exceptions')], default='', max_length=50),
        ),
    ]
