# Generated by Django 3.0.3 on 2020-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0067_auto_20200222_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_panel_spec',
            name='row_parameter_prefix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
