# Generated by Django 3.0.3 on 2020-02-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0068_dashboard_panel_spec_row_parameter_prefix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Panel_Column_Inclusion',
            new_name='Panel_Column_In_Panel',
        ),
    ]
