# Generated by Django 3.0.3 on 2020-02-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0069_auto_20200222_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Column_Inclusion',
            new_name='Column_In_Dashboard',
        ),
    ]
