# Generated by Django 3.0.3 on 2020-02-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0070_auto_20200222_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Panel_Inclusion',
            new_name='Panel_In_Column',
        ),
    ]
