# Generated by Django 3.0.3 on 2020-02-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0072_auto_20200222_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Spec',
            new_name='Dashboard',
        ),
        migrations.RenameField(
            model_name='column_in_dashboard',
            old_name='dashboard_spec',
            new_name='dashboard',
        ),
    ]
