# Generated by Django 3.0.3 on 2020-02-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0073_auto_20200222_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column_in_dashboard',
            options={'ordering': ['order'], 'verbose_name_plural': 'columns in dashboards'},
        ),
    ]
