# Generated by Django 3.0.3 on 2020-02-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0074_auto_20200222_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Column_Spec',
            new_name='Column',
        ),
        migrations.AlterModelOptions(
            name='column_in_dashboard',
            options={'verbose_name_plural': 'columns in dashboards'},
        ),
        migrations.RenameField(
            model_name='column_in_dashboard',
            old_name='dashboard_column_spec',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='panel_in_column',
            old_name='dashboard_column_spec',
            new_name='column',
        ),
    ]
