# Generated by Django 3.0.3 on 2020-02-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0075_auto_20200222_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name_plural': 'columns'},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['name'], 'verbose_name_plural': 'dashboards'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name'], 'verbose_name_plural': 'panels'},
        ),
    ]
