# Generated by Django 3.0.3 on 2020-02-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0076_auto_20200222_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard_Panel_Column_Spec',
            new_name='Panel_Column',
        ),
        migrations.AlterModelOptions(
            name='panel_column',
            options={'ordering': ['name'], 'verbose_name_plural': 'panel columns'},
        ),
        migrations.AlterModelOptions(
            name='panel_column_in_panel',
            options={'ordering': ('panel__name', 'order'), 'verbose_name_plural': 'panel columns in panels'},
        ),
        migrations.RenameField(
            model_name='panel_column_in_panel',
            old_name='dashboard_panel_column_spec',
            new_name='panel_column',
        ),
    ]
