# Generated by Django 3.0.3 on 2020-03-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0077_auto_20200222_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
