# Generated by Django 3.0.3 on 2020-03-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0078_dashboard_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Dashboard'),
        ),
    ]
