# Generated by Django 3.0.3 on 2020-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0079_site_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='sub_filters',
            field=models.ManyToManyField(blank=True, related_name='owning_panels', to='people.Filter_Spec'),
        ),
    ]
