# Generated by Django 3.0.3 on 2020-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0081_panel_column_apply_sub_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='abss_type',
            name='membership_number_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='membership_number',
            field=models.IntegerField(default=0),
        ),
    ]
