# Generated by Django 3.0.3 on 2020-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0082_auto_20200322_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
