# Generated by Django 3.0.3 on 2020-03-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0083_option_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_code',
            options={'ordering': ('post_code',), 'verbose_name_plural': 'post codes'},
        ),
    ]
