# Generated by Django 3.0.3 on 2020-04-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0085_venue_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Venue_Type'),
            preserve_default=False,
        ),
    ]
