# Generated by Django 3.0.3 on 2020-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0087_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='email_address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='facilities',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='mobile_phone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_hours',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
