# Generated by Django 3.0.3 on 2020-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0091_auto_20200425_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation_step',
            options={'ordering': ('-datetime_created', 'invitation_step_type__order'), 'verbose_name_plural': 'invitation steps'},
        ),
        migrations.AlterField(
            model_name='invitation_step_type',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
