# Generated by Django 3.0.3 on 2020-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0092_auto_20200425_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_step_type',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
