# Generated by Django 3.0.3 on 2020-04-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0093_invitation_step_type_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='invitations_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
