# Generated by Django 3.0.3 on 2020-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0094_auto_20200426_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation_step',
            options={'ordering': ('invitation_step_type__order',), 'verbose_name_plural': 'invitation steps'},
        ),
        migrations.AddField(
            model_name='question',
            name='use_for_invitations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation_step_type',
            name='name',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('personal_details', 'Personal Details'), ('address', 'Address'), ('children', 'Children')], max_length=50),
        ),
    ]
