# Generated by Django 3.0.3 on 2020-04-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0095_auto_20200426_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_step_type',
            name='name',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('personal_details', 'Personal Details'), ('address', 'Address'), ('children', 'Children'), ('questions', 'Questions')], max_length=50),
        ),
    ]
