# Generated by Django 3.0.3 on 2020-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0096_auto_20200426_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
