# Generated by Django 3.0.3 on 2020-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0097_invitation_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
