# Generated by Django 3.0.3 on 2020-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0098_invitation_invalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms_and_conditions',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
    ]
