# Generated by Django 3.0.3 on 2020-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0100_invitation_step_type_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship_type',
            name='use_for_invitations',
            field=models.BooleanField(default=False),
        ),
    ]
