# Generated by Django 3.0.3 on 2020-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0101_relationship_type_use_for_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='invitaton_introduction',
            field=models.TextField(blank=True, default='', max_length=25000),
        ),
    ]
