# Generated by Django 3.0.3 on 2020-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0102_site_invitaton_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='invitaton_introduction',
            new_name='invitation_introduction',
        ),
        migrations.AlterField(
            model_name='invitation_step_type',
            name='name',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('terms_and_conditions', 'Terms and Conditions'), ('personal_details', 'Personal Details'), ('address', 'Address'), ('children', 'Children'), ('questions', 'Questions')], max_length=50),
        ),
    ]
