# Generated by Django 3.0.3 on 2020-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0104_auto_20200524_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
