# Generated by Django 3.0.3 on 2020-05-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0105_venue_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='otp_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_logins', models.IntegerField(default=0)),
                ('unsuccessful_logins', models.IntegerField(default=0)),
                ('successful_otp_logins', models.IntegerField(default=0)),
                ('unsuccessful_otp_logins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
