# Generated by Django 3.0.3 on 2020-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0106_auto_20200525_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='password_reset_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='password_reset_text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
