# Generated by Django 3.0.3 on 2020-05-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0107_auto_20200530_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_resets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='successful_resets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='password_reset_timeout',
            field=models.IntegerField(default=15),
        ),
    ]
