# Generated by Django 3.0.3 on 2020-05-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0108_auto_20200530_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='password_reset_text',
            new_name='password_reset_email_text',
        ),
    ]
