# Generated by Django 3.0.3 on 2020-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0111_auto_20200530_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
