# Generated by Django 3.0.7 on 2020-06-06 09:06

from django.db import migrations, models
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0113_panel_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='chart',
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chart_type', models.CharField(blank=True, choices=[('pie', 'Pie Chart'), ('bar', 'Bar Chart'), ('month_bar', 'Bar Chart by Month')], default='', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('count_field', models.CharField(max_length=50)),
                ('filters', models.ManyToManyField(blank=True, to='people.Filter_Spec')),
            ],
            options={
                'verbose_name_plural': 'charts',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
