# Generated by Django 3.0.7 on 2020-06-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0114_auto_20200606_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Chart'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='panel',
            name='row_name_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
