# Generated by Django 3.0.7 on 2020-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0115_auto_20200606_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='label_field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
