# Generated by Django 3.0.7 on 2020-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0117_auto_20200606_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='date_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chart',
            name='months',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='sort_field',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
