# Generated by Django 3.0.7 on 2020-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0119_auto_20200606_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='many_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chart',
            name='query_type',
            field=models.CharField(blank=True, choices=[('query from one', 'query from one'), ('query from many', 'query from many')], default='query from one', max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
