# Generated by Django 3.0.7 on 2020-06-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0120_auto_20200606_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='sum_field',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
