# Generated by Django 3.0.7 on 2020-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0121_chart_sum_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='super_filters',
            field=models.ManyToManyField(blank=True, related_name='owning_charts', to='people.Filter_Spec'),
        ),
        migrations.AlterField(
            model_name='filter_spec',
            name='period',
            field=models.CharField(blank=True, choices=[('', 'no period'), ('this_month', 'this month'), ('last_month', 'last_month'), ('this_project_year', 'this project year'), ('last_project_year', 'last project year'), ('this_calendar_year', 'this calendar year'), ('last_calendar_year', 'last_calendar_year'), ('rolling_quarter', 'rolling_quarter')], default='', max_length=50),
        ),
    ]
