# Generated by Django 3.0.7 on 2020-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0123_auto_20200606_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='x_label_rotation',
            field=models.IntegerField(default=0),
        ),
    ]
