# Generated by Django 3.0.7 on 2020-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0124_chart_x_label_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='group_by_field',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
