# Generated by Django 3.0.7 on 2020-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0125_chart_group_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='period',
            field=models.CharField(blank=True, choices=[('', 'no period'), ('this_month', 'this month'), ('last_month', 'last_month'), ('this_project_year', 'this project year'), ('last_project_year', 'last project year'), ('this_calendar_year', 'this calendar year'), ('last_calendar_year', 'last_calendar_year'), ('rolling_quarter', 'rolling_quarter')], default='', max_length=50),
        ),
    ]
