# Generated by Django 3.0.7 on 2020-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0127_auto_20200608_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='facilities',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
