# Generated by Django 3.0.7 on 2020-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0130_filter_spec_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='password_reset_email_cc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
