# Generated by Django 3.0.7 on 2020-06-27 09:49

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0132_auto_20200621_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_step',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation_step_type',
            name='name',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('terms_and_conditions', 'Terms and Conditions'), ('personal_details', 'Personal Details'), ('address', 'Address'), ('children', 'Children'), ('questions', 'Questions'), ('signature', 'Signature')], max_length=50),
        ),
    ]
