# Generated by Django 3.0.7 on 2020-06-27 09:57

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0133_auto_20200627_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation_step',
            name='signature',
        ),
        migrations.AddField(
            model_name='invitation',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
