# Generated by Django 3.0.7 on 2020-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0135_auto_20200628_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation_step',
            options={'ordering': ['-datetime_created'], 'verbose_name_plural': 'invitation steps'},
        ),
        migrations.AlterField(
            model_name='invitation_step_type',
            name='data_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('table', 'table'), ('fields', 'fields'), ('signature', 'signature')], default='', max_length=50),
        ),
    ]
