# Generated by Django 3.0.7 on 2020-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0137_auto_20200628_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='signature',
        ),
    ]
