# Generated by Django 3.0.7 on 2020-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0138_remove_invitation_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_step_type',
            name='special_category_text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
