# Generated by Django 3.0.7 on 2020-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0139_invitation_step_type_special_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_step',
            name='special_category_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
