# Generated by Django 3.0.7 on 2020-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0140_invitation_step_special_category_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='use_for_children_form',
            field=models.BooleanField(default=False),
        ),
    ]
