# Generated by Django 3.0.7 on 2020-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0142_registration_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_form',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
