# Generated by Django 3.0.7 on 2020-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0144_question_use_for_invitations_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=7500),
        ),
    ]
