# Generated by Django 3.0.7 on 2020-08-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0146_registration_form_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_form',
            name='logo',
        ),
    ]
