# Generated by Django 3.0.7 on 2020-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0147_remove_registration_form_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_form',
            name='logo_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
