# Generated by Django 3.0.7 on 2020-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0148_registration_form_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trained_role',
            name='date_trained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
