# Generated by Django 3.0.7 on 2020-08-29 13:52

from django.db import migrations, models
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0150_auto_20200818_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'document links',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
