# Generated by Django 3.0.7 on 2020-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0151_document_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document_link',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'document links'},
        ),
        migrations.AddField(
            model_name='document_link',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document_link',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
