# Generated by Django 3.0.7 on 2020-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0153_auto_20200830_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_type',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
