# Generated by Django 3.0.7 on 2020-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0154_auto_20200906_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='max_login_attempts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
