# Generated by Django 3.0.7 on 2020-11-08 14:51

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0156_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('membership_number_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'membership types',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Membership_Type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Project')),
            ],
            options={
                'verbose_name_plural': 'memberships',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.AddField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(through='people.Membership', to='people.Project'),
        ),
    ]
