# Generated by Django 3.0.7 on 2020-11-15 16:08

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0160_activity_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Project')),
            ],
            options={
                'verbose_name_plural': 'project permissions',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(through='people.Project_Permission', to='people.Project'),
        ),
    ]
