# Generated by Django 3.0.7 on 2020-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0161_auto_20201115_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='projects_active',
            field=models.BooleanField(default=False),
        ),
    ]
