# Generated by Django 3.0.7 on 2020-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0162_site_projects_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='abss_type',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership_type',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
