# Generated by Django 3.0.7 on 2020-12-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0164_ethnicity_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='abss_type',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Membership_Type'),
        ),
    ]
