# Generated by Django 3.0.7 on 2021-01-04 15:02

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0165_abss_type_membership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Event_Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Project')),
            ],
            options={
                'verbose_name_plural': 'project event types',
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.AddField(
            model_name='event_type',
            name='projects',
            field=models.ManyToManyField(through='people.Project_Event_Type', to='people.Project'),
        ),
    ]
