# Generated by Django 3.0.7 on 2021-03-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0166_auto_20210104_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abss_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'ABSS types'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('person__last_name', 'person__first_name', 'activity_type__name'), 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='activity_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'activity types'},
        ),
        migrations.AlterModelOptions(
            name='age_status',
            options={'ordering': ('status',), 'verbose_name_plural': 'Age statuses'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('person__first_name', 'person__last_name', 'question__order'), 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='answer_note',
            options={'ordering': ('person__first_name', 'person__last_name', 'question__order'), 'verbose_name_plural': 'answer notes'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('area_name',), 'verbose_name_plural': 'areas'},
        ),
        migrations.AlterModelOptions(
            name='column_in_dashboard',
            options={'ordering': ('dashboard__name', 'column__name', 'order'), 'verbose_name_plural': 'columns in dashboards'},
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'ordering': ('description',), 'verbose_name_plural': 'ethnicities'},
        ),
        migrations.AlterModelOptions(
            name='event_category',
            options={'ordering': ('name',), 'verbose_name_plural': 'event categories'},
        ),
        migrations.AlterModelOptions(
            name='event_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'event types'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ('person__last_name', 'person__first_name', 'datetime_created'), 'verbose_name_plural': 'invitations'},
        ),
        migrations.AlterModelOptions(
            name='invitation_step',
            options={'ordering': ('invitation__person__last_name', 'invitation__person__first_name', 'invitation_step_type__order'), 'verbose_name_plural': 'invitation steps'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('person__last_name', 'person__first_name'), 'verbose_name_plural': 'memberships'},
        ),
        migrations.AlterModelOptions(
            name='membership_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'membership types'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('option_label',), 'verbose_name_plural': 'options'},
        ),
        migrations.AlterModelOptions(
            name='panel_in_column',
            options={'ordering': ('column__name', 'panel__name', 'order'), 'verbose_name_plural': 'panels in columns'},
        ),
        migrations.AlterModelOptions(
            name='printform_data_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'printform data types'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__username',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='project_event_type',
            options={'ordering': ('event_type__name',), 'verbose_name_plural': 'project event types'},
        ),
        migrations.AlterModelOptions(
            name='project_permission',
            options={'ordering': ('project__name', 'profile__user__username'), 'verbose_name_plural': 'project permissions'},
        ),
        migrations.AlterModelOptions(
            name='registration_form',
            options={'ordering': ('name',), 'verbose_name_plural': 'registration forms'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ('relationship_from__last_name', 'relationship_from__first_name', 'relationship_type__relationship_type'), 'verbose_name_plural': 'memberships'},
        ),
        migrations.AlterModelOptions(
            name='relationship_type',
            options={'ordering': ('relationship_type',), 'verbose_name_plural': 'relationship types'},
        ),
        migrations.AlterModelOptions(
            name='role_history',
            options={'ordering': ('person__last_name', 'person__first_name', 'started'), 'verbose_name_plural': 'role histories'},
        ),
        migrations.AlterModelOptions(
            name='role_type',
            options={'ordering': ('role_type_name',), 'verbose_name_plural': 'role types'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='terms_and_conditions',
            options={'ordering': ('name',), 'verbose_name_plural': 'terms and conditions'},
        ),
        migrations.AlterModelOptions(
            name='trained_role',
            options={'ordering': ('person__last_name', 'person__first_name', 'role_type__role_type_name'), 'verbose_name_plural': 'trained roles'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',), 'verbose_name_plural': 'venues'},
        ),
        migrations.AlterModelOptions(
            name='venue_type',
            options={'ordering': ('name',), 'verbose_name_plural': 'venue types'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ('ward_name',), 'verbose_name_plural': 'wards'},
        ),
    ]
