# Generated by Django 3.0.7 on 2021-03-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0167_auto_20210327_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_permission',
            options={'ordering': ('profile__user__username', 'project__name'), 'verbose_name_plural': 'project permissions'},
        ),
    ]
