# Generated by Django 3.0.7 on 2021-03-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0168_auto_20210327_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ('relationship_from__last_name', 'relationship_from__first_name', 'relationship_type__relationship_type'), 'verbose_name_plural': 'relationships'},
        ),
    ]
