# Generated by Django 3.1.9 on 2021-06-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0169_auto_20210327_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.project'),
        ),
    ]
