# Generated by Django 3.1.9 on 2021-06-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0170_question_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='project',
        ),
    ]
