# Generated by Django 3.1.9 on 2021-06-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0171_remove_question_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='projects',
            field=models.ManyToManyField(blank=True, to='people.Family'),
        ),
    ]
