# Generated by Django 3.1.9 on 2021-06-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0174_auto_20210612_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_section',
            options={'ordering': ('order',), 'verbose_name_plural': 'question sections'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.question_section'),
        ),
    ]
