# Generated by Django 3.1.12 on 2021-08-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0176_case_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_notes',
            old_name='notes_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='case_notes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.project'),
        ),
        migrations.AlterField(
            model_name='case_notes',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
    ]
