# Generated by Django 3.1.12 on 2021-08-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0177_auto_20210821_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case_notes',
            options={'ordering': ['-date'], 'verbose_name_plural': 'case notes'},
        ),
    ]
