# Generated by Django 3.1.12 on 2021-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0178_auto_20210821_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_notes',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
