# Generated by Django 3.1.13 on 2021-12-28 07:12

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0179_case_notes_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1500)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.project')),
            ],
            options={
                'verbose_name_plural': 'survey series',
                'ordering': ['title'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
