# Generated by Django 3.1.13 on 2021-12-28 07:29

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0181_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.survey_series'),
        ),
        migrations.CreateModel(
            name='Survey_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.survey')),
            ],
            options={
                'verbose_name_plural': 'survey sections',
                'ordering': ['order'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
