# Generated by Django 3.1.13 on 2021-12-28 09:39

from django.db import migrations, models
import django.db.models.deletion
import people.django_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0183_auto_20211228_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Question_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'survey question types',
                'ordering': ['name'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('question', models.CharField(blank=True, default='', max_length=500)),
                ('survey_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.survey_section')),
            ],
            options={
                'verbose_name_plural': 'survey sections',
                'ordering': ['survey_section__survey__name', 'survey_section__name', 'number'],
            },
            bases=(people.django_extensions.DataAccessMixin, models.Model),
        ),
    ]
