# Generated by Django 3.1.13 on 2021-12-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0185_auto_20211228_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_question',
            name='survey_question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.survey_question_type'),
        ),
    ]
