# Generated by Django 3.1.13 on 2021-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0186_survey_question_survey_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_question',
            name='options',
            field=models.IntegerField(default=0),
        ),
    ]
