# Generated by Django 3.1.13 on 2021-12-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0187_survey_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_question_type',
            name='options_required',
            field=models.BooleanField(default=False),
        ),
    ]
