# Generated by Django 3.1.13 on 2021-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0188_survey_question_type_options_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_question_type',
            name='text_required',
            field=models.BooleanField(default=False),
        ),
    ]
