# Generated by Django 3.1.14 on 2022-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0190_auto_20211229_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
    ]
