# Generated by Django 3.1.14 on 2022-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0191_age_status_minimum_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_status',
            name='use_for_automated_categorisation',
            field=models.BooleanField(default=True),
        ),
    ]
