# Generated by Django 2.1.5 on 2019-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190217_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'age statuses',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.AlterModelOptions(
            name='relationship_type',
            options={'verbose_name_plural': 'relationship types'},
        ),
        migrations.AddField(
            model_name='person',
            name='families',
            field=models.ManyToManyField(to='people.Family'),
        ),
    ]
