# Generated by Django 2.1.5 on 2019-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='english_is_second_language',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
