# Generated by Django 2.1.5 on 2019-03-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_english_is_second_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ethnicity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Ethnicity'),
        ),
    ]
