# Generated by Django 2.1.5 on 2019-03-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190303_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Children_Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_centre_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'children centres',
            },
        ),
        migrations.AlterModelOptions(
            name='role_type',
            options={'verbose_name_plural': 'role types'},
        ),
        migrations.AddField(
            model_name='cc_registration',
            name='children_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Children_Centre'),
        ),
        migrations.AddField(
            model_name='cc_registration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='children_centres',
            field=models.ManyToManyField(through='people.CC_Registration', to='people.Children_Centre'),
        ),
    ]
