# Generated by Django 2.1.5 on 2019-03-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190303_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age_Status',
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
