# Generated by Django 2.1.5 on 2019-03-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190303_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='savs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
