# Generated by Django 2.1.5 on 2019-03-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20190307_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'answers'},
        ),
    ]
