# Generated by Django 2.1.5 on 2019-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20190307_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_names',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
