# Generated by Django 2.1.5 on 2019-03-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20190309_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='english_is_second_language',
            field=models.BooleanField(default=False),
        ),
    ]
