name: Betterstart

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install mysql-server
        sudo apt-get install libmysqlclient-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Database setup
      run: |
        python manage.py migrate
      env:
        BETTERSTART_DB: local
    - name: Local django test
      run: |
        python manage.py test
      env:
        BETTERSTART_DB: local
    - name: Install Google tools
      run : |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-271.0.0-linux-x86_64.tar.gz
        tar zxvf google-cloud-sdk-271.0.0-linux-x86_64.tar.gz google-cloud-sdk
        curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
        chmod +x cloud_sql_proxy
    - name: System test
      run: |
        # authorise GCP SDK
        echo $BETTERSTART_GCP_KEYFILE > keyfile
        google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=keyfile
        google-cloud-sdk/bin/gcloud sql databases list --instance=betterstart
      env:
        BETTERSTART_GCP_KEYFILE: ${{ secrets.systest_BETTERSTART_GCP_KEYFILE }}
